#### Question 7:

In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv("../data/ames_prices.csv")
df["central_air"] = (df["Central.Air"] == "Y").astype(int)
x = df["central_air"]
n = len(x)

# a: 
p_hat = x.mean()
print(p_hat)

0.9331058020477816

In [2]:
# b:

seed, B = 42, 2000
rng = np.random.default_rng(seed)
boot = np.array([rng.choice(x, size=n, replace=True).mean() for _ in range(B)])

In [3]:
# c:
se = boot.std(ddof=1)
print(se)

0.004590333440769273

In [4]:
# d:
lo_90 = p_hat - 1.645 * se
hi_90 = p_hat + 1.645 * se

lo_95 = p_hat - 1.96 * se
hi_95 = p_hat + 1.96 * se

lo_99 = p_hat - 2.576 * se
hi_99 = p_hat + 2.576 * se

print(f"90% CI: ({lo_90:.3f}, {hi_90:.3f})")
print(f"95% CI: ({lo_95:.3f}, {hi_95:.3f})")
print(f"99% CI: ({lo_99:.3f}, {hi_99:.3f})")

90% CI: (0.926, 0.941)
95% CI: (0.924, 0.942)
99% CI: (0.921, 0.945)

In [5]:
# e:

p0 = 0.90

print("alpha = 0.10:", "fail to reject the null hypothesis" if lo_90 <= p0 <= hi_90 
      else "reject the null hypothesis")
print("alpha = 0.05:", "fail to reject the null hypothesis" if lo_95 <= p0 <= hi_95 
      else "reject the null hypothesis")
print("alpha = 0.01:", "fail to reject the null hypothesis" if lo_99 <= p0 <= hi_99 
      else "reject the null hypothesis")

alpha = 0.10: reject the null hypothesis
alpha = 0.05: reject the null hypothesis
alpha = 0.01: reject the null hypothesis

**None of the confidence intervals contain 0.90 so they all reject the null hypothesis.**

#### Question 8:

In [6]:
x_q8 = np.arcsinh(df["area"])
y_q8 = np.arcsinh(df["price"])
n_q8 = len(x_q8)

orig_est = np.corrcoef(x_q8, y_q8)[0, 1]
print(orig_est)

0.7231661530091356

In [7]:
# a:
# 
# Used ai to help with the for loop. 
seed, B = 42, 2000
rng = np.random.default_rng(seed)
boot = np.empty(B)
for b in range(B):
    idx = rng.integers(0, n_q8, size=n_q8)
    boot[b] = np.corrcoef(x_q8[idx], y_q8[idx])[0, 1]

In [8]:
# b:

se = boot.std(ddof=1)
print(se)

0.010285986570021796

In [9]:
# c:

lo_90, hi_90 = orig_est - 1.645 * se, orig_est + 1.645 * se
lo_95, hi_95 = orig_est - 1.96 * se,  orig_est + 1.96 * se
lo_99, hi_99 = orig_est - 2.576 * se, orig_est + 2.576 * se

print(f"90% CI: ({lo_90:.3f}, {hi_90:.3f})")
print(f"95% CI: ({lo_95:.3f}, {hi_95:.3f})")
print(f"99% CI: ({lo_99:.3f}, {hi_99:.3f})")

90% CI: (0.706, 0.740)
95% CI: (0.703, 0.743)
99% CI: (0.697, 0.750)

In [10]:
# d: 

print("alpha = 0.10:", "fail to reject the null hypothesis" if lo_90 <= p0 <= hi_90 
      else "reject the null hypothesis")
print("alpha = 0.05:", "fail to reject the null hypothesis" if lo_95 <= p0 <= hi_95 
      else "reject the null hypothesis")
print("alpha = 0.01:", "fail to reject the null hypothesis" if lo_99 <= p0 <= hi_99 
      else "reject the null hypothesis")

alpha = 0.10: reject the null hypothesis
alpha = 0.05: reject the null hypothesis
alpha = 0.01: reject the null hypothesis

**Since the null hypothesis is rejected, and the CI are betwen 0.697-0.75, this means that as area increases, price increases.**

**e:** Area and price must be resampled together otherwise they would be paired with random houses if done separately.

#### Question 9:

In [11]:
metabric = pd.read_csv("../data/metabric.csv")

x_q9 = metabric["Overall Survival (Months)"]
n_q9 = len(x_q9)

mean_hat = x_q9.mean()
print(mean_hat)

129.09429138744105

In [12]:
# a:

seed, B = 42, 2000
rng = np.random.default_rng(seed)
boot = np.empty(B)
for b in range(B):
    boot[b] = rng.choice(x_q9, size=n_q9, replace=True).mean()

In [13]:
# b: 

se = boot.std(ddof=1)
print(se)

2.135806001210453

In [14]:
# c:

lo_90, hi_90 = mean_hat - 1.645 * se, mean_hat + 1.645 * se
lo_95, hi_95 = mean_hat - 1.96 * se,  mean_hat + 1.96 * se
lo_99, hi_99 = mean_hat - 2.576 * se, mean_hat + 2.576 * se

print(f"90% CI: ({lo_90:.3f}, {hi_90:.3f})")
print(f"95% CI: ({lo_95:.3f}, {hi_95:.3f})")
print(f"99% CI: ({lo_99:.3f}, {hi_99:.3f})")

90% CI: (125.581, 132.608)
95% CI: (124.908, 133.280)
99% CI: (123.592, 134.596)

In [15]:
# d:
u = 120

print("alpha = 0.10:", "fail to reject the null hypothesis" if lo_90 <= u <= hi_90 
      else "reject the null hypothesis")
print("alpha = 0.05:", "fail to reject the null hypothesis" if lo_95 <= u <= hi_95 
      else "reject the null hypothesis")
print("alpha = 0.01:", "fail to reject the null hypothesis" if lo_99 <= u <= hi_99 
      else "reject the null hypothesis")

alpha = 0.10: reject the null hypothesis
alpha = 0.05: reject the null hypothesis
alpha = 0.01: reject the null hypothesis

**e:** The estimate is 129 months (10.8 years) and the confidence intervals have it between 123 to 134 months (10.25 - 11.17 years). The results do not estimate the unrestricted mean lifetime because the living patients are only recording their last follow up.

#### Question 10:

In [16]:
data = pd.read_csv("../data/nhanes_data_17_18.csv")
meta = pd.read_csv("../data/nhanes_meta_17_18.csv")

# used ai to help with this, was not using double brackets [[]] at the end,
# ai corrected it.
meta[meta["Label"].str.contains("age", case=False, na=False)][["VariableNameLong", "Variable", "Label"]]

C:\Users\alvar\AppData\Local\Temp\ipykernel_28944\1777141744.py:1: DtypeWarning: Columns (142: ServedActiveDutyInUsArmedForces) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("../data/nhanes_data_17_18.csv")

,VariableNameLong,Variable,Label
2,AgeStoppedBreastfeedingdays,DBD030,Age stopped breastfeeding(days)
3,AgeFirstFedFormuladays,DBD041,Age first fed formula(days)
4,AgeStoppedReceivingFormuladays,DBD050,Age stopped receiving formula(days)
5,AgeStartedOtherFoodbeverage,DBD055,Age started other food/beverage
6,AgeFirstFedMilkdays,DBD061,Age first fed milk(days)
22,HowOftenDrankMilkAge512,DBQ235A,How often drank milk age 5-12
23,HowOftenDrankMilkAge1317,DBQ235B,How often drank milk age 13-17
24,HowOftenDrankMilkAge1835,DBQ235C,How often drank milk age 18-35
115,AgeWhenToldYouHadHeartAttack,MCD180E,Age when told you had heart attack
117,AgeWhenToldYouHadAStroke,MCD180F,Age when told you had a stroke
120,Age1StCancerMcq230ADiagnosed,MCD240A,Age 1st cancer (MCQ230a) diagnosed
137,AgeInYearsAtScreening,RIDAGEYR,Age in years at screening
138,AgeInMonthsAtScreening0To24Mos,RIDAGEMN,Age in months at screening - 0 to 24 mos
176,AgeWhenFirstToldYouHadDiabetes,DID040,Age when first told you had diabetes
185,AgeStartedSmokingCigarettesRegularly,SMD030,Age started smoking cigarettes regularly

In [17]:
meta[meta["VariableNameLong"].str.contains("SleepHoursWeekdaysOrWorkdays")][["VariableNameLong", "Variable"]]

                VariableNameLong Variable
59  SleepHoursWeekdaysOrWorkdays   SLD012

In [18]:
print(data["SleepHoursWeekdaysOrWorkdays"].isna().sum())

2583

In [19]:
adults = data[(data["AgeInYearsAtScreening"] >= 18) &
              (data["SleepHoursWeekdaysOrWorkdays"].notna())]

x10 = adults["SleepHoursWeekdaysOrWorkdays"]
n = len(x10)

mean_hat = x10.mean()
print(mean_hat)

7.62124248496994

In [20]:
# a:

seed, B = 42, 2000
rng = np.random.default_rng(seed)
boot = np.empty(B)
for b in range(B):
    boot[b] = rng.choice(x10, size=n, replace=True).mean()

In [21]:
# b:

se = boot.std(ddof=1)
print(se)

0.022750666141160076

In [22]:
# c:

lo_90, hi_90 = mean_hat - 1.645 * se, mean_hat + 1.645 * se
lo_95, hi_95 = mean_hat - 1.96 * se,  mean_hat + 1.96 * se
lo_99, hi_99 = mean_hat - 2.576 * se, mean_hat + 2.576 * se

print(f"90% CI: ({lo_90:.3f}, {hi_90:.3f})")
print(f"95% CI: ({lo_95:.3f}, {hi_95:.3f})")
print(f"99% CI: ({lo_99:.3f}, {hi_99:.3f})")

90% CI: (7.584, 7.659)
95% CI: (7.577, 7.666)
99% CI: (7.563, 7.680)

In [24]:
# d:

mu = 8

print("alpha = 0.10:", "fail to reject the null hypothesis" if lo_90 <= mu <= hi_90 
      else "reject the null hypothesis")
print("alpha = 0.05:", "fail to reject the null hypothesis" if lo_95 <= mu <= hi_95 
      else "reject the null hypothesis")
print("alpha = 0.01:", "fail to reject the null hypothesis" if lo_99 <= mu <= hi_99 
      else "reject the null hypothesis")

alpha = 0.10: reject the null hypothesis
alpha = 0.05: reject the null hypothesis
alpha = 0.01: reject the null hypothesis

**e:** The statistical evidence shows that the respondents were getting less than 8 hours of sleep per night. This is because the initial mean estimate is 7.62 and the confidence intervals are below 8 as well. From a practical standpoint, the difference is around 23 minutes which is not that much a difference. For example, if I were to lose 23 minutes of sleep, it would not have much of an effect on me compared to if I were to lose an hour of sleep. The practical siginficance differs from the statistical signficance which is indicating that it is a meaningful difference.